version: "3.8"

services:
  orion:
    image: fiware/orion
    hostname: orion
    container_name: fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    command: -dbhost mongodb
    networks:
      - fiware_network

  iot-agent:
    image: fiware/iotagent-json:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    expose:
      - "4041"
      - "7896"
    ports:
      - "4041:4041"
      - "7896:7896"
    depends_on:
      - mongodb
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongo_db
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongodb
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentjson
      - IOTA_HTTP_PORT=7896
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json
    networks:
      - fiware_network

  mongodb:
    image: mongo:4.4
    hostname: mongodb
    container_name: db-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fiware_network

  crate-db:
      image: crate:latest
      hostname: crate-db
      ports:
        - "4200:4200"
        - "4300:4300"
        - "5432:5432"
      command: crate -Cauth.host_based.enabled=false -Ccluster.name=democluster -Chttp.cors.enabled=true -Cnode.store.allow_mmap=false -Chttp.cors.allow-origin='*'
      environment:
        - CRATE_HEAP_SIZE=2g
      volumes:
        - ./data/crate:/data/crate-db-data
      networks:
      - fiware_network

  
  quantumleap:
    image: smartsdk/quantumleap
    hostname: quantumleap
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db
      - LOGLEVEL=DEBUG
    networks:
      - fiware_network

 

  grafana:
    image: grafana/grafana
    depends_on:
      - crate-db
    ports:
      - "3003:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - fiware_network

networks:
  fiware_network:


volumes:
  mongodb_data: ~
  crate-db_data: ~
  grafana: ~
