version: "3.8"

services:
  orion:
    image: fiware/orion
    hostname: orion
    container_name: fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    command: -dbhost mongodb
    networks:
      - fiware_network

  iot-agent:
    image:  fiware/iotagent-json:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    expose:
        - "4041"
        - "7896"
    ports:
      - "4041:4041"
      - "7896:7896"
    depends_on:
      - mongodb
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongo_db
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongodb
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentjson
      - IOTA_HTTP_PORT=7896
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json
    networks:
      - fiware_network

  mongodb:
    image: mongo:4.4
    hostname: mongodb
    container_name: db-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fiware_network

  quantumleap:
    image: smartsdk/quantumleap
    hostname: quantumleap
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - QL_DB_BACKEND=crate-db
      - QL_DB_URI=http://crate:4200
      - QL_LOG_LEVEL=DEBUG
    networks:
      - fiware_network

  crate-db:
    image: crate:4.1.4
    hostname: crate-db
    ports:
        - "4200:4200"
        - "4300:4300"
    command:
        crate -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true
        -Chttp.cors.allow-origin="*"
    environment:
        - CRATE_HEAP_SIZE=2g

  grafana:
    image: grafana/grafana
    depends_on:
        - crate-db
    ports:
        - "3003:3000"
    environment:
        - GF_INSTALL_PLUGINS=https://github.com/orchestracities/grafana-map-plugin/archive/master.zip;grafana-map-plugin,grafana-clock-panel,grafana-worldmap-panel

networks:
  fiware_network:


volumes:
  mongodb_data:
  crate-db_data:


